services:

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  eureka-client:
    build: ./eureka-client
    depends_on:
      - eureka-server

  product-service:
    build: ./product-service
    ports:
      - "8088:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-product-db:3306/productservicedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=cokgizlisifre
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
    depends_on:
      - eureka-server
      - mysql-product-db
    
  mysql-product-db:
    image: mysql:8.0
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=cokgizlisifre
      - MYSQL_DATABASE=productservicedb
    volumes:
      - mysql_product_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pcokgizlisifre"]
      timeout: 20s
      retries: 10


  user-service:
    build: ./user-service
    ports:
      - "8089:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-user-db:3306/userservicedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=cokgizlisifre
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
    depends_on:
      - eureka-server
      - mysql-user-db

  mysql-user-db:
    image: mysql:8.0
    ports:
      - "33062:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=cokgizlisifre
      - MYSQL_DATABASE=userservicedb
    volumes:
      - mysql_user_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pcokgizlisifre"]
      timeout: 20s
      retries: 10

volumes:
  mysql_product_data:
  mysql_user_data:
