spring:
  application:
    name: order-service

  sql:
    init:
      mode: always

  datasource:
    username: orderdbuser
    url: jdbc:mysql://mysql-db:3306/orderservicedb
    password: cokgizlisifre

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,traces,circuitbreakers,prometheus

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false

opentelemetry:
  service:
    name: order-service
  exporter:
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans

#resilience4j:
#  circuitbreaker:
#    instances:
#      get-user-CB:
#        slidingWindowSize: 5
#        minimumNumberOfCalls: 5
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#        permittedNumberOfCallsInHalfOpenState: 2
#        automaticTransitionFromOpenToHalfOpenEnabled: true
