spring:
  application:
    name: product-service

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    username: productdbuser
    url: jdbc:mysql://mysql-db:3306/productservicedb
    password: cokgizlisifre

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,traces

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false

opentelemetry:
  service:
    name: user-service
  exporter:
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans
