INSERT INTO products (name, description, price, stock_quantity)
VALUES ('Laptop Pro X1', 'High-performance laptop for professionals, 16GB RAM, 512GB SSD.', 1299.99, 50),
       ('UltraBook Slim Y2', 'Lightweight and sleek ultrabook, perfect for travel, 13-inch display.', 999.50, 75),
       ('SmartPhone Z Max', 'Latest generation smartphone with advanced camera and 128GB storage.', 799.00, 120),
       ('PixelMobile G5', 'Flagship phone with pure Android experience and excellent camera.', 649.99, 90),
       ('TabPro S7', '11-inch tablet with powerful processor and S-Pen support.', 450.00, 60),
       ('MiniTablet A3', 'Compact 8-inch tablet, great for reading and media consumption.', 220.75, 110),
       ('HD Monitor 27"', '27-inch Full HD IPS monitor with vibrant colors.', 249.99, 80),
       ('Curved Gaming Display 32"', '32-inch QHD curved monitor with 144Hz refresh rate for immersive gaming.', 479.50,
        40),
       ('Mechanical Keyboard RGB',
        'Full-size mechanical keyboard with customizable RGB backlighting and blue switches.', 120.00, 150),
       ('Wireless Ergonomic Keyboard', 'Split ergonomic keyboard designed for comfort during long typing sessions.',
        89.99, 95),
       ('Gaming Mouse Pro', 'High-precision gaming mouse with adjustable DPI and programmable buttons.', 59.99, 200),
       ('Bluetooth Travel Mouse', 'Compact and lightweight wireless mouse, ideal for laptops.', 25.50, 180),
       ('Noise-Cancelling Headphones', 'Over-ear headphones with active noise cancellation and long battery life.',
        199.99, 70),
       ('Wireless Earbuds X20', 'True wireless earbuds with charging case and clear sound quality.', 79.00, 250),
       ('HD Webcam 1080p', 'Webcam with Full HD resolution and built-in microphone for video conferencing.', 45.00,
        130),
       ('Conference Cam Pro', 'Professional webcam with wide-angle lens and stereo microphones for meeting rooms.',
        150.99, 30),
       ('All-in-One Printer Color', 'Multifunction color inkjet printer with scan, copy, and Wi-Fi.', 99.99, 65),
       ('Laser Printer Mono', 'Monochrome laser printer for fast and efficient black & white printing.', 130.00, 55),
       ('SSD 1TB NVMe', '1TB NVMe M.2 Solid State Drive for ultra-fast storage performance.', 110.50, 100),
       ('External HDD 2TB USB 3.0', '2TB portable external hard drive for backups and extra storage.', 69.99, 140),
       ('Ergonomic Office Chair Deluxe', 'High-back ergonomic chair with lumbar support and adjustable armrests.',
        299.00, 25),
       ('Mesh Back Office Chair', 'Breathable mesh back chair for comfortable all-day use.', 159.99, 45),
       ('Standing Desk Electric Pro', 'Electric height-adjustable standing desk, 48x30 inches.', 399.00, 15),
       ('Gaming Desk Large RGB', 'Spacious gaming desk with RGB lighting and carbon fiber texture.', 220.50, 20),
       ('Productivity Suite Pro 2025',
        'Office software suite including word processor, spreadsheet, and presentation tools.', 149.99, 500),
       ('Antivirus Ultimate Security', 'Comprehensive antivirus and internet security software for 3 devices.', 49.99,
        300),
       ('USB-C Hub 7-in-1', 'Multiport USB-C adapter with HDMI, USB 3.0, SD card reader, and Ethernet.', 35.00, 160),
       ('HDMI Cable 2m High Speed', '2-meter 4K HDMI cable for connecting displays and devices.', 12.99, 300),
       ('Smart Speaker Mini Gen 2', 'Compact smart speaker with voice assistant and improved sound.', 49.00, 90),
       ('VR Headset Advanced Kit', 'Virtual reality headset with controllers for immersive experiences.', 399.99, 35),
       ('Graphics Tablet Medium', 'Drawing tablet with 8192 pressure sensitivity levels for digital artists.', 79.99,
        50),
       ('Portable Power Bank 20000mAh', 'High-capacity power bank for charging multiple devices on the go.', 39.99,
        120),
       ('Laptop Stand Adjustable', 'Ergonomic aluminum laptop stand for better posture and cooling.', 28.50, 100),
       ('Wireless Charger Pad 15W', 'Fast wireless charging pad compatible with Qi-enabled devices.', 19.99, 200),
       ('Smartwatch Fitness Tracker', 'Smartwatch with heart rate monitor, GPS, and multiple sport modes.', 129.00, 85),
       ('Digital Photo Frame 10-inch', 'Wi-Fi enabled digital photo frame to display your favorite memories.', 89.00,
        40),
       ('Bluetooth Speaker Portable Waterproof', 'Rugged and waterproof Bluetooth speaker for outdoor use.', 55.99,
        110),
       ('Router Wi-Fi 6 AX3000', 'Next-gen Wi-Fi 6 router for faster speeds and better coverage.', 149.00, 60),
       ('Network Attached Storage (NAS) 2-Bay', 'Diskless 2-bay NAS for creating your personal cloud storage.', 199.99,
        20),
       ('MicroSD Card 256GB U3', 'High-speed 256GB microSD card for cameras, drones, and phones.', 32.50, 150),
       ('USB Flash Drive 128GB 3.1', '128GB USB 3.1 flash drive for fast data transfer.', 18.99, 220),
       ('Monitor Arm Single Gas Spring', 'Adjustable single monitor arm for ergonomic screen positioning.', 45.00, 70),
       ('Document Scanner Portable', 'Compact document scanner for digitizing papers on the go.', 99.00, 30),
       ('Projector Mini HD LED', 'Portable LED projector for home entertainment and presentations.', 130.99, 25),
       ('Gaming Headset Surround Sound', 'Wired gaming headset with 7.1 surround sound and noise-cancelling mic.',
        69.99, 90),
       ('External SSD 500GB USB-C', '500GB portable SSD with USB-C for fast external storage.', 75.00, 80),
       ('Laptop Cooling Pad with Fans', 'Cooling pad with multiple fans to prevent laptop overheating.', 22.00, 120),
       ('Presentation Clicker Wireless', 'Wireless presenter remote with laser pointer for professional presentations.',
        15.99, 100),
       ('Cable Management Sleeves (4-pack)', 'Set of 4 neoprene cable sleeves to organize messy wires.', 10.50, 300),
       ('Desk Lamp LED with USB Charging', 'Adjustable LED desk lamp with multiple brightness levels and USB port.',
        32.00, 75),
       ('Smart Plug Wi-Fi (2-pack)', 'Control your appliances remotely with these Wi-Fi smart plugs.', 24.99, 110),
       ('Security Camera Indoor 1080p', 'Wi-Fi indoor security camera with night vision and two-way audio.', 39.00, 60),
       ('Action Camera 4K Waterproof', 'Waterproof action camera for capturing adventures in 4K.', 119.99, 40),
       ('Drone Quadcopter with Camera HD', 'Beginner-friendly drone with HD camera and easy controls.', 89.99, 30),
       ('E-Reader GlowLight 6-inch', '6-inch e-reader with adjustable front light for comfortable reading.', 129.00,
        50),
       ('Soundbar 2.1 Channel with Subwoofer', 'Soundbar system for enhancing TV audio experience.', 149.50, 35),
       ('Backpack Laptop 15.6-inch Anti-Theft', 'Durable and secure laptop backpack with USB charging port.', 42.00,
        90),
       ('Mouse Pad Extended Gaming', 'Large gaming mouse pad with smooth surface and non-slip base.', 17.99, 180),
       ('UPS Mini 800VA', 'Uninterruptible Power Supply to protect electronics from power outages.', 85.00, 25),
       ('Thermal Paste High Performance', 'CPU thermal paste for optimal heat dissipation.', 8.99, 200),
       ('Screen Cleaning Kit', 'Kit with spray and microfiber cloth for cleaning screens.', 9.50, 150),
       ('USB-C to Lightning Cable 1m MFi', 'Apple MFi certified USB-C to Lightning cable for charging and syncing.',
        14.99, 120),
       ('Ethernet Cable Cat 7 5m', '5-meter Cat 7 shielded Ethernet cable for high-speed networking.', 11.00, 250),
       ('External Blu-Ray Writer USB 3.0', 'Portable Blu-Ray writer and DVD burner.', 79.00, 15),
       ('Digital Voice Recorder 16GB', 'Compact voice recorder for lectures and interviews.', 33.00, 60),
       ('Label Maker Portable QWERTY', 'Handheld label maker with QWERTY keyboard.', 29.99, 40),
       ('Paper Shredder 8-Sheet Cross-Cut', 'Cross-cut paper shredder for secure document disposal.', 45.00, 30),
       ('Whiteboard Magnetic Dry Erase 24x36', 'Magnetic whiteboard for brainstorming and notes.', 38.00, 20),
       ('Desk Organizer Mesh Metal', 'Multi-compartment desk organizer for pens, notes, and supplies.', 16.50, 100),
       ('Foot Rest Ergonomic Under Desk', 'Adjustable foot rest to improve posture and circulation.', 26.99, 50),
       ('Laptop Sleeve 14-inch Neoprene', 'Protective neoprene sleeve for 14-inch laptops.', 12.00, 90),
       ('Smart Light Bulb RGBW Wi-Fi (4-pack)', 'Color-changing smart bulbs controllable via app or voice.', 39.99, 70),
       ('Car Phone Mount Universal Air Vent', 'Adjustable car phone holder for air vents.', 11.99, 130),
       ('Travel Adapter Universal All-in-One', 'International travel adapter for multiple countries.', 19.00, 80),
       ('Portable SSD Enclosure M.2 NVMe USB-C', 'Enclosure to turn an NVMe SSD into a portable drive.', 28.00, 45),
       ('Gaming Chair Racing Style High Back', 'Ergonomic gaming chair with reclining function and footrest.', 189.99,
        18),
       ('VR Stand and Charging Station', 'Stand to store and charge VR headset and controllers.', 34.50, 22),
       ('Condenser Microphone USB Studio Kit', 'USB microphone kit for podcasting, streaming, and recording.', 75.00,
        33),
       ('Green Screen Collapsible 5x7ft', 'Portable green screen for video production and streaming.', 55.00, 28),
       ('Ring Light 10-inch with Tripod Stand', 'LED ring light for video calls, streaming, and photography.', 27.99,
        65),
       ('Laptop Privacy Screen 14-inch', 'Privacy filter for 14-inch laptop screens.', 21.00, 55),
       ('Wireless Presenter with Air Mouse', 'Advanced presenter with air mouse functionality.', 32.00, 30),
       ('Stylus Pen for Touch Screens Universal', 'Active stylus pen compatible with most touch screen devices.', 18.50,
        95),
       ('Portable Scanner Wand', 'Handheld scanner for quickly digitizing documents and photos.', 65.00, 20),
       ('Smart Thermostat Wi-Fi Programmable', 'Energy-saving smart thermostat controllable via app.', 129.99, 15),
       ('Electric Standing Desk Converter', 'Adjustable converter to turn any desk into a standing desk.', 149.00, 25),
       ('Monitor Riser Stand Wood', 'Wooden monitor stand with space for keyboard storage underneath.', 29.00, 40),
       ('Anti-Fatigue Mat for Standing Desks', 'Comfortable mat for use with standing desks.', 35.00, 30),
       ('Cable Clips Organizer (100-pack)', 'Adhesive cable clips for managing wires on desks and walls.', 9.99, 200),
       ('USB C to HDMI Adapter 4K', 'Adapter to connect USB-C devices to HDMI displays.', 16.00, 80),
       ('Wireless Keyboard and Mouse Combo Quiet', 'Full-size quiet keyboard and mouse set.', 38.99, 70),
       ('External DVD Drive USB 3.0 Portable', 'Slim portable external CD/DVD reader and writer.', 26.00, 50),
       ('Gaming Mouse Bungee Cable Management', 'Device to prevent mouse cable drag for smoother gaming.', 13.50, 60),
       ('Headphone Stand with USB Hub', 'Desk stand for headphones with built-in USB 3.0 hub.', 23.00, 40),
       ('Smart Water Bottle Stainless Steel', 'Tracks water intake and glows to remind you to drink.', 39.99, 25),
       ('Portable Bluetooth Label Printer', 'Compact label printer connecting via Bluetooth to your phone.', 42.00, 30),
       ('Ergonomic Vertical Mouse Wireless', 'Reduces wrist strain with a vertical handshake design.', 27.50, 45),
       ('Laptop Lock Cable Security', 'Universal security cable lock for laptops.', 14.00, 70),
       ('Mini Projector Screen 50-inch Portable', 'Foldable projector screen for small presentations or movies.', 35.99,
        15),
       ('USB C Power Adapter 65W GaN Fast Charger', 'Compact and powerful GaN charger for laptops and phones.', 29.99,
        85);